nodeLinker: node-modules
npmScopes:
  avada:
    npmRegistryServer: "https://registry.avada.io"
    npmAlwaysAuth: true
    npmAuthToken: "OUujf6Frq8k2UbEfzZDK3QKYR0AmYmPZsYBA89LdnIk="

  shopify:
    npmRegistryServer: "https://registry2.avada.io"