# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24d55558fc419649abaec3931705b48a"
name = "dev-test1"
handle = "dev-test1"
application_url = "https://fly-beef-tablet-links.trycloudflare.com/auth/shopify"
embedded = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://fly-beef-tablet-links.trycloudflare.com/auth/shopify/callback",
  "https://fly-beef-tablet-links.trycloudflare.com/authSa/shopify/callback",
  "https://fly-beef-tablet-links.trycloudflare.com/auth/shopify/embed/callback",
  "https://fly-beef-tablet-links.trycloudflare.com/auth/shopify/embed/callback/updateScopes",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[[extensions]]
type = "theme"
name = "avada-sales-pop"
path = "extensions/avada-sales-pop"
