type="frontend"
port=3000
auth_callback_path = ["/auth/shopify/callback", "/authSa/shopify/callback", "/auth/shopify/embed/callback", "/auth/shopify/embed/callback/updateScopes"]

[commands]
dev = "npm run watch:embed"
build = "npm run production"
